<script src="<?php echo $rootUri; ?>www/js/jquery.dataTables.min.js"></script>
<script src="<?php echo $rootUri; ?>www/js/jquery.dataTables.bootstrap.js"></script>
<script src="<?php echo $rootUri; ?>www/js/jquery.dataTables.columnFilter.js"></script>
<script src="<?php echo $rootUri?>www/js/jquery-ui-1.10.3.full.min.js"></script>
<script src="<?php echo $rootUri?>www/js/jquery.ui.touch-punch.min.js"></script>
<script src="<?php echo $rootUri?>www/js/jquery.easy-pie-chart.min.js"></script>
<script src="<?php echo $rootUri?>www/js/flot/jquery.flot.min.js"></script>
<script src="<?php echo $rootUri?>www/js/flot/jquery.flot.pie.min.js"></script>
<script src="<?php echo $rootUri?>www/plug-in/DatePicker/WdatePicker.js"></script>
